### ISSUE TITLE
ClubSweetheart URL Apostrophe

### ISSUE THREAD

**Issue by HWatBobby** [PAhelper/PhoenixAdult.bundle#1248]
**Describe the bug**
When matching scenes from ClubSweethearts the utility will add an apostrophe to words that commonly have apostrophes and then start the search, which fails because the url should not have an apostrophe in it.

**Include**
1. URL:
``https://www.clubseventeen.com/video.php?slug=please_dont_cry``

2. File Name:
``ClubSweethearts - 2021-01-18 - [Young Lesbian Lovers] - Please Dont Cry [Maya Morgan, Darey Dark]``

3. Log File: 
```
2021-04-04 09:36:01,879 (146a5ec90700) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo1Mzg5MDA4NjI1ZDc0NWEzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczYyCkNsdWJzd2VldGhlYXJ0cyAyMDIxIDAxIDMxIEJsb25kZXMgRG9udCBHaXZlIGEgRnVjayAxNjExODQ3NzA3czQKbmFtZXMxNjQKJTJGcHJpdmF0ZSUyRkNsdWJTZXZlbnRlZW4lMkZDbHViU3dlZXRoZWFydHMlMjAtJTIwMjAyMS0wMS0zMSUyMC0lMjAlNUJCbG9uZGUlMjBUZWVucyU1RCUyMC0lMjBCbG9uZGVzJTIwRG9udCUyMEdpdmUlMjBBJTIwRnVjayUyMDE2MTE4NDc3MDclMjAlNUJDYXNleSUyMEklNUQlMkVtcDRzOApmaWxlbmFtZXM0MApmNTZkMmU3YWQxN2ZlMzZiNTQ5ZTM4YWM4M2NkZmQ1MzYwY2M5MTA5czgKcGxleEhhc2hzNgo3NDgxNjBzOApkdXJhdGlvbnM1Cjg3MDc4czIKaWRyMAo_
2021-04-04 09:36:01,880 (146a5ec90700) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-04-04 09:36:01,881 (146a5ec90700) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo1Mzg5MDA4NjI1ZDc0NWEzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczYyCkNsdWJzd2VldGhlYXJ0cyAyMDIxIDAxIDMxIEJsb25kZXMgRG9udCBHaXZlIGEgRnVjayAxNjExODQ3NzA3czQKbmFtZXMxNjQKJTJGcHJpdmF0ZSUyRkNsdWJTZXZlbnRlZW4lMkZDbHViU3dlZXRoZWFydHMlMjAtJTIwMjAyMS0wMS0zMSUyMC0lMjAlNUJCbG9uZGUlMjBUZWVucyU1RCUyMC0lMjBCbG9uZGVzJTIwRG9udCUyMEdpdmUlMjBBJTIwRnVjayUyMDE2MTE4NDc3MDclMjAlNUJDYXNleSUyMEklNUQlMkVtcDRzOApmaWxlbmFtZXM0MApmNTZkMmU3YWQxN2ZlMzZiNTQ5ZTM4YWM4M2NkZmQ1MzYwY2M5MTA5czgKcGxleEhhc2hzNgo3NDgxNjBzOApkdXJhdGlvbnM1Cjg3MDc4czIKaWRyMAo_
2021-04-04 09:36:01,881 (146a5ec90700) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': '5389008625d745a3', 'name': 'Clubsweethearts 2021 01 31 Blondes Dont Give a Fuck 1611847707', 'filename': '%2Fprivate%2FClubSeventeen%2FClubSweethearts%20-%202021-01-31%20-%20%5BBlonde%20Teens%5D%20-%20Blondes%20Dont%20Give%20A%20Fuck%201611847707%20%5BCasey%20I%5D%2Emp4', 'plexHash': 'f56d2e7ad17fe36b549e38ac83cdfd5360cc9109', 'duration': '748160', 'id': '87078'}
2021-04-04 09:36:01,881 (146a5ec90700) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/87078/tree'
2021-04-04 09:36:01,888 (146a5ec90700) :  INFO (__init__:63) - ***MEDIA TITLE [from media.name]*** Clubsweethearts 2021 01 31 Blondes Dont Give a Fuck 1611847707
2021-04-04 09:36:01,888 (146a5ec90700) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Clubsweethearts 2021 01 31 Blondes Dont Give a Fuck 1611847707
2021-04-04 09:36:01,901 (146a5ec90700) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Clubsweethearts 2021 01 31 Blondes Dont Give a Fuck 1611847707
2021-04-04 09:36:01,909 (146a5ec90700) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 800
2021-04-04 09:36:01,910 (146a5ec90700) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2021-04-04 09:36:01,911 (146a5ec90700) :  INFO (PAsearchSites:95) - Search Title (before date processing): 2021 01 31 Blondes Don't Give a Fuck 1611847707
2021-04-04 09:36:01,911 (146a5ec90700) :  INFO (__init__:65) - {'siteName': 'clubsweethearts', 'searchDate': '2021-01-31', 'siteNum': 800, 'searchTitle': "Blondes Don't Give a Fuck 1611847707"}
2021-04-04 09:36:01,912 (146a5ec90700) :  INFO (PAsearchData:19) - SearchData.title: Blondes Don't Give a Fuck 1611847707
2021-04-04 09:36:01,912 (146a5ec90700) :  INFO (PAsearchData:22) - SearchData.date: 2021-01-31
2021-04-04 09:36:01,912 (146a5ec90700) :  INFO (PAsearchData:25) - SearchData.filename: ClubSweethearts - 2021-01-31 - [Blonde Teens] - Blondes Dont Give A Fuck 1611847707 [Casey I]
2021-04-04 09:36:01,912 (146a5ec90700) :  INFO (__init__:95) - Provider: siteClubSweethearts
2021-04-04 09:36:01,914 (146a5ec90700) :  INFO (PAutils:175) - Requesting GET "https://www.clubsweethearts.com/video.php?slug=Blondes_Don't_Give_a_Fuck_1611847707"
2021-04-04 09:36:03,014 (146a5ec90700) :  ERROR (__init__:99) - Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 97, in search
    provider.search(results, lang, siteNum, search)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteClubSweethearts.py", line 11, in search
    titleNoFormatting = detailsPageElements.xpath('//h3[@class="dvd-title mb-0 mt-0"]/span')[0].text_content().strip()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-3cbd5e781/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2021-04-04 09:36:03,016 (146a5ec90700) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-04-04 09:36:03,016 (146a5ec90700) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
```

**Comment by DirtyRacer1337** [comment]
Fixed in fd6ee72933a5631e7e00792b3288543f96c8f04c
