### ISSUE TITLE
Nympho error in matching

### ISSUE THREAD

**Issue by covrdinbeez** [PAhelper/PhoenixAdult.bundle#1250]
**Describe the bug**
Matching isn't returning results directly from Nympho (MetaDataAPI is though.) From the log below, it looks like it might be choking on a possibly changed element in the Nympho pages?
I am seeing the same error on multiple Nympho matches.

**Include**
1. Scene URL: https://tour.nympho.com/view/slut-party-with-natalie-and-avery
2. File Name: Nympho.19.10.27.Slut.Party.With.Natalie.and.Avery.XXX.1080p.HEVC.x265
3. Log File
```
2021-04-04 15:07:36,121 (70000316a000) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2Cjc3NTgyM3MyCmlkczQ5Ck55bXBoby4xOS4xMC4yNy5TbHV0LlBhcnR5LldpdGguTmF0YWxpZS5hbmQuQXZlcnlzNApuYW1lczQKMjAxOXM0CnllYXJyMAo_
2021-04-04 15:07:36,122 (70000316a000) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-04-04 15:07:36,123 (70000316a000) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2Cjc3NTgyM3MyCmlkczQ5Ck55bXBoby4xOS4xMC4yNy5TbHV0LlBhcnR5LldpdGguTmF0YWxpZS5hbmQuQXZlcnlzNApuYW1lczQKMjAxOXM0CnllYXJyMAo_
2021-04-04 15:07:36,123 (70000316a000) :  INFO (agentkit:961) - Searching for matches for {'year': '2019', 'id': '775823', 'name': 'Nympho.19.10.27.Slut.Party.With.Natalie.and.Avery'}
2021-04-04 15:07:36,123 (70000316a000) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/775823/tree'
2021-04-04 15:07:36,128 (70000316a000) :  INFO (__init__:63) - ***MEDIA TITLE [from media.name]*** Nympho.19.10.27.Slut.Party.With.Natalie.and.Avery
2021-04-04 15:07:36,128 (70000316a000) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Nympho.19.10.27.Slut.Party.With.Natalie.and.Avery
2021-04-04 15:07:36,135 (70000316a000) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Nympho.19.10.27.Slut.Party.With.Natalie.and.Avery
2021-04-04 15:07:36,139 (70000316a000) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 284
2021-04-04 15:07:36,139 (70000316a000) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2021-04-04 15:07:36,140 (70000316a000) :  INFO (PAsearchSites:95) - Search Title (before date processing): 19 10 27 Slut Party with Natalie and Avery
2021-04-04 15:07:36,140 (70000316a000) :  INFO (__init__:65) - {'siteName': 'nympho', 'searchDate': '2019-10-27', 'siteNum': 284, 'searchTitle': 'Slut Party with Natalie and Avery'}
2021-04-04 15:07:36,140 (70000316a000) :  INFO (PAsearchData:19) - SearchData.title: Slut Party with Natalie and Avery
2021-04-04 15:07:36,140 (70000316a000) :  INFO (PAsearchData:22) - SearchData.date: 2019-10-27
2021-04-04 15:07:36,140 (70000316a000) :  INFO (__init__:95) - Provider: networkSteppedUp
2021-04-04 15:07:36,141 (70000316a000) :  INFO (PAutils:175) - Requesting GET "https://tour.nympho.com/view/slut-party-with-natalie-and-avery"
2021-04-04 15:07:36,209 (70000316a000) :  ERROR (__init__:99) - Traceback (most recent call last):
  File "/Users/batcave/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 97, in search
    provider.search(results, lang, siteNum, search)
  File "/Users/batcave/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkSteppedUp.py", line 15, in search
    titleNoFormatting = detailsPageElements.xpath('//h1[@class="title"] | //h2[@class="title"]')[0].text_content().strip()
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-3cbd5e781/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2021-04-04 15:07:36,213 (70000316a000) :  INFO (__init__:107) - Provider: networkMetadataAPI
2021-04-04 15:07:36,214 (70000316a000) :  INFO (PAutils:175) - Requesting GET "https://api.metadataapi.net/scenes?parse=Slut%20Party%20with%20Natalie%20and%20Avery"
2021-04-04 15:07:36,702 (70000316a000) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-04-04 15:07:36,702 (70000316a000) :  DEBUG (runtime:924) - Response: [200] str, 704 bytes
```

**Comment by DirtyRacer1337** [comment]
Same as #951

**Comment by covrdinbeez** [comment]
Gotcha. I didn't think the HTML error meant that, but I see now.
