### ISSUE TITLE
ReidMyLips isn't matching

### ISSUE THREAD

**Issue by MrDemous** [PAhelper/PhoenixAdult.bundle#1287]
**Describe the bug**
reidmylips.com isn't matching

**Include**
1. https://reidmylips.com/updates/New-Years-Resolution-Anal.html
2. ReidMyLips - New Years Resolution Anal
3. 

> 2021-05-17 04:18:30,678 (52b4) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** ReidMyLips - New Years Resolution Anal
2021-05-17 04:18:30,678 (52b4) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: ReidMyLips - New Years Resolution Anal
2021-05-17 04:18:30,686 (52b4) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: ReidMyLips - New Years Resolution Anal
2021-05-17 04:18:30,690 (52b4) :  INFO (logkit:16) - ^^^^^^^ siteNum: 803
2021-05-17 04:18:30,690 (52b4) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2021-05-17 04:18:30,691 (52b4) :  INFO (logkit:16) - Search Title (before date processing): New Years Resolution Anal
2021-05-17 04:18:30,693 (52b4) :  INFO (logkit:16) - {'siteName': 'reidmylips', 'searchDate': None, 'siteNum': 803, 'searchTitle': 'New Years Resolution Anal'}
2021-05-17 04:18:30,693 (52b4) :  INFO (logkit:16) - SearchData.title: New Years Resolution Anal
2021-05-17 04:18:30,693 (52b4) :  INFO (logkit:16) - Provider: siteReidMyLips
2021-05-17 04:18:30,694 (52b4) :  INFO (logkit:16) - Requesting GET "https://www.reidmylips.com/new-years-resolution-anal"
2021-05-17 04:18:31,115 (52b4) :  ERROR (logkit:22) - Traceback (most recent call last):
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 102, in search
    provider.search(results, lang, siteNum, search)
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\siteReidMyLips.py", line 11, in search
    curID = PAutils.Encode(url)
NameError: global name 'url' is not defined

**Comment by DirtyRacer1337** [comment]
Try with this 3b01039319d68b7656578da249a5c2acfd27ea90

**Comment by MrDemous** [comment]
It's matching now but it doesn't pull Actors, date, poster, or background.

**Comment by DirtyRacer1337** [comment]
Looks like I fixed it in latest commit, but site have protection

**Comment by MrDemous** [comment]
It's fixed now, thanks @DirtyRacer1337

**Comment by MrDemous** [comment]
It's down again and giving this error

> 2021-05-19 00:12:33,709 (35fc) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** Reidmylips Christmas Bonus
2021-05-19 00:12:33,710 (35fc) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Reidmylips Christmas Bonus
2021-05-19 00:12:33,717 (35fc) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Reidmylips Christmas Bonus
2021-05-19 00:12:33,723 (35fc) :  INFO (logkit:16) - ^^^^^^^ siteNum: 803
2021-05-19 00:12:33,723 (35fc) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2021-05-19 00:12:33,724 (35fc) :  INFO (logkit:16) - Search Title (before date processing): Christmas Bonus
2021-05-19 00:12:33,724 (35fc) :  INFO (logkit:16) - {'siteName': 'reidmylips', 'searchDate': None, 'siteNum': 803, 'searchTitle': 'Christmas Bonus'}
2021-05-19 00:12:33,726 (35fc) :  INFO (logkit:16) - SearchData.title: Christmas Bonus
2021-05-19 00:12:33,726 (35fc) :  INFO (logkit:16) - SearchData.filename: ReidMyLips - Christmas Bonus
2021-05-19 00:12:33,726 (35fc) :  INFO (logkit:16) - Provider: siteReidMyLips
2021-05-19 00:12:33,726 (35fc) :  INFO (logkit:16) - Requesting GET "https://www.reidmylips.com/updates/christmas-bonus.html"
2021-05-19 00:12:34,349 (35fc) :  ERROR (logkit:22) - Traceback (most recent call last):
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 102, in search
    provider.search(results, lang, siteNum, search)
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\siteReidMyLips.py", line 11, in search
    titleNoFormatting = detailsPageElements.xpath('//span[@class="update_title"]')[0].text_content().strip()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-d0ce30438\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

**Comment by DirtyRacer1337** [comment]
I already told you, site have protection

**Comment by MrDemous** [comment]
I didn't really know what that meant but I thought it was fixed because I managed to match a couple of scenes from it earlier. My bad.
