### ISSUE TITLE
VirtualRealPorn Match Issue

### ISSUE THREAD

**Issue by nerfdaderp** [PAhelper/PhoenixAdult.bundle#1306]
**Describe the bug**
While the fix detailed here (https://github.com/PAhelper/PhoenixAdult.bundle/issues/1296) does work for the majority of the videos using the new folder structure, it does not seem to work for those videos not contained in a subfolder, nor within a folder of "big-ass" for example. It seems it is breaking on the GET request for the examples below.

**Include**
1. Scene URL
https://virtualrealporn.com/vr-porn-video/taking-care-of-you/ - searaching as "virtualrealporn - taking-care-of-you/"
https://virtualrealporn.com/vr-porn-video/big-ass/escaping-the-friend-zone/ searching as "virtualrealporn - big-ass/escaping-the-friend-zone/"

2. File Name
3. Log File

From looking athe logs, it looks like the path gets parsed incorrectly on the GET request.

```
2021-06-05 08:10:17,745 (7f19a025db38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 342
2021-06-05 08:10:17,746 (7f19a025db38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2021-06-05 08:10:17,748 (7f19a025db38) :  INFO (PAsearchSites:95) - Search Title (before date processing): Big Ass Escaping the Friend Zone
2021-06-05 08:10:17,749 (7f19a025db38) :  INFO (__init__:61) - {'siteName': 'virtualrealporn', 'searchDate': None, 'siteNum': 342, 'searchTitle': 'Big Ass Escaping the Friend Zone'}
2021-06-05 08:10:17,749 (7f19a025db38) :  INFO (PAsearchData:22) - SearchData.title: Big Ass Escaping the Friend Zone
2021-06-05 08:10:17,749 (7f19a025db38) :  INFO (__init__:98) - Provider: siteVirtualReal
2021-06-05 08:10:17,752 (7f19a025db38) :  INFO (PAutils:182) - Requesting GET "https://virtualrealporn.com/vr-porn-video/big/ass-escaping-the-friend-zone"
2021-06-05 08:10:17,958 (7f19a025db38) :  ERROR (__init__:102) - Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 100, in search
    provider.search(results, lang, siteNum, search)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteVirtualReal.py", line 13, in search
    titleNoFormatting = sceneData['name'].split('|')[0].strip()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-85f0adf5b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
KeyError: 'name'

2021-06-05 08:10:17,960 (7f19a025db38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-06-05 08:10:17,961 (7f19a025db38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes


Amarna Miller - Taking Care of You
2021-06-05 08:15:42,287 (7f19a025db38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2021-06-05 08:15:42,289 (7f19a025db38) :  INFO (PAsearchSites:95) - Search Title (before date processing): Taking Care of You
2021-06-05 08:15:42,290 (7f19a025db38) :  INFO (__init__:61) - {'siteName': 'virtualrealporn', 'searchDate': None, 'siteNum': 342, 'searchTitle': 'Taking Care of You'}
2021-06-05 08:15:42,290 (7f19a025db38) :  INFO (PAsearchData:22) - SearchData.title: Taking Care of You
2021-06-05 08:15:42,290 (7f19a025db38) :  INFO (__init__:98) - Provider: siteVirtualReal
2021-06-05 08:15:42,292 (7f19a025db38) :  **INFO (PAutils:182) - Requesting GET "https://virtualrealporn.com/vr-porn-video/taking/care-of-you"**
2021-06-05 08:15:43,158 (7f19a025db38) :  ERROR (__init__:102) - Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 100, in search
    provider.search(results, lang, siteNum, search)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteVirtualReal.py", line 13, in search
    titleNoFormatting = sceneData['name'].split('|')[0].strip()
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-85f0adf5b/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
KeyError: 'name'

2021-06-05 08:15:43,160 (7f19a025db38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-06-05 08:15:43,161 (7f19a025db38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
```

**Comment by DirtyRacer1337** [comment]
Try with 3267f4a3b849c2c73769ca1e1c098b4e2cb5f340, and rename this file `virtualrealporn - big-ass/escaping-the-friend-zone/` to `virtualrealporn - escaping-the-friend-zone`

**Comment by nerfdaderp** [comment]
Awesome, thank you for the quick turnaround too. I had about 80 or so of these scenes which would not match; every one I have tried so far since the new push have matched successfully.

hanks again!!
