### ISSUE TITLE
mypervyfamily issue

### ISSUE THREAD

**Issue by boivinx7** [PAhelper/PhoenixAdult.bundle#1331]
Seems to have the right search string in the logs, but its not finding it in the end. 

**Include**
1. https://www.mypervyfamily.com/824512/my-pervy-family-shy-step-daughters-indecent-proposal-streaming-scene-video.html
2. My Pervy Family - 2021.03.15 - Shy Step-Daughter's Indecent Proposal
3. [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/6721773/com.plexapp.agents.phoenixadult.log)

**Comment by xnwabudike** [comment]
This applies to all of AdultEmpireCash as they made some slight design changes.

**Comment by oikmeg** [comment]
I am also having issues with this site:
```
2021-07-12 16:45:30,328 (14e1f6232b38) :  INFO (__init__:59) - ***MEDIA TITLE [from media.name]*** Mypervyfamily 20 02 18 Lexi Luna
2021-07-12 16:45:30,329 (14e1f6232b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Mypervyfamily 20 02 18 Lexi Luna
2021-07-12 16:45:30,341 (14e1f6232b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Mypervyfamily 20 02 18 Lexi Luna
2021-07-12 16:45:30,350 (14e1f6232b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 1248
2021-07-12 16:45:30,350 (14e1f6232b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2021-07-12 16:45:30,352 (14e1f6232b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): 20 02 18 Lexi Luna
2021-07-12 16:45:30,353 (14e1f6232b38) :  INFO (__init__:61) - {'siteName': 'mypervyfamily', 'searchDate': '2020-02-18', 'siteNum': 1248, 'searchTitle': 'Lexi Luna'}
2021-07-12 16:45:30,353 (14e1f6232b38) :  INFO (PAsearchData:23) - SearchData.title: Lexi Luna
2021-07-12 16:45:30,354 (14e1f6232b38) :  INFO (PAsearchData:26) - SearchData.date: 2020-02-18
2021-07-12 16:45:30,354 (14e1f6232b38) :  INFO (PAsearchData:29) - SearchData.filename: mypervyfamily.20.02.18.lexi.luna.4k
2021-07-12 16:45:30,354 (14e1f6232b38) :  INFO (__init__:98) - Provider: networkAdultEmpireCash
2021-07-12 16:45:30,356 (14e1f6232b38) :  INFO (PAutils:182) - Requesting GET "https://www.mypervyfamily.com/MemberSceneSearch?q=Lexi%20Luna"
2021-07-12 16:45:30,592 (14e1f6232b38) :  ERROR (__init__:102) - Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 100, in search
    provider.search(results, lang, siteNum, search)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkAdultEmpireCash.py", line 9, in search
    titleNoFormatting = searchResult.xpath('.//a[@class="grid-item-title"]/text()')[0]
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-186bae04e/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
```

**Comment by Mr575** [comment]
Not good site
