### ISSUE TITLE
Brazzers not working

### ISSUE THREAD

**Issue by MrDemous** [PAhelper/PhoenixAdult.bundle#1332]
**Describe the bug**
Brazzers isn't working and giving an error in logs.

**Include**
1. https://www.brazzers.com/video/4459551/butts-in-sync
2. Brazzers - Butts in Sync
3. 

> 2021-06-27 17:01:01,959 (46f4) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** Brazzers Butts in Sync
2021-06-27 17:01:01,959 (46f4) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Brazzers Butts in Sync
2021-06-27 17:01:01,967 (46f4) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Brazzers Butts in Sync
2021-06-27 17:01:01,973 (46f4) :  INFO (logkit:16) - ^^^^^^^ siteNum: 2
2021-06-27 17:01:01,973 (46f4) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2021-06-27 17:01:01,974 (46f4) :  INFO (logkit:16) - Search Title (before date processing): Butts in Sync
2021-06-27 17:01:01,974 (46f4) :  INFO (logkit:16) - {'siteName': 'brazzers', 'searchDate': None, 'siteNum': 2, 'searchTitle': u'Butts in Sync'}
2021-06-27 17:01:01,974 (46f4) :  INFO (logkit:16) - SearchData.title: Butts in Sync
2021-06-27 17:01:01,974 (46f4) :  INFO (logkit:16) - Provider: network1service
2021-06-27 17:01:01,976 (46f4) :  ERROR (logkit:22) - Traceback (most recent call last):
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 100, in search
    provider.search(results, lang, siteNum, search)
  File "C:\Users\demou\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network1service.py", line 37, in search
    if unicode(parts[0], 'UTF-8').isdigit():
TypeError: decoding Unicode is not supported
2021-06-27 17:01:01,982 (46f4) :  INFO (logkit:16) - Provider: networkMetadataAPI
2021-06-27 17:01:01,983 (46f4) :  INFO (logkit:16) - Requesting GET "https://api.metadataapi.net/scenes?parse=Butts%20in%20Sync"
2021-06-27 17:01:02,881 (46f4) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-06-27 17:01:02,881 (46f4) :  DEBUG (runtime:924) - Response: [200] str, 688 bytes

**Comment by DirtyRacer1337** [comment]
Fixed in 0e8b6ec462d973ce7259420d833491d04fd2050a
