### ISSUE TITLE
Jayspov stopped working

### ISSUE THREAD

**Issue by hrmieon31** [PAhelper/PhoenixAdult.bundle#1342]
When i identify a movie as a jayspov doesnt find matches

I open the Matcher then i put "JaysPOV.19.10.12.Lexi.Luna.Horny.Hot.Mom.Demands.Her.Stepsons.Cock.XXX"
and nothing matches the search

**Comment by DirtyRacer1337** [comment]
logs

**Comment by xnwabudike** [comment]
As I mentioned over in the following issue:  https://github.com/PAhelper/PhoenixAdult.bundle/issues/1331

AdultEmpireCash made some slight design changes so afaik all sites under that umbrella are broken. On top of that JaysPOV has additional differences from other sites on that network.

```
2021-07-10 00:44:42,585 (cd4) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** JaysPOV Petite Yumi Sin Tiny Asian Casting
2021-07-10 00:44:42,585 (cd4) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: JaysPOV Petite Yumi Sin Tiny Asian Casting
2021-07-10 00:44:42,585 (cd4) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: JaysPOV Petite Yumi Sin Tiny Asian Casting
2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - ^^^^^^^ siteNum: 815
2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - Search Title (before date processing): Petite Yumi Sin Tiny Asian Casting
2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - {'siteName': 'jayspov', 'searchDate': None, 'siteNum': 815, 'searchTitle': 'Petite Yumi Sin Tiny Asian Casting'}
2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - SearchData.title: Petite Yumi Sin Tiny Asian Casting
2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - SearchData.filename: JaysPOV - Petite Yumi Sin Tiny Asian Casting
2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - Provider: networkAdultEmpireCash
2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - Requesting GET "https://jayspov.net/MemberSceneSearch?q=Petite%20Yumi%20Sin%20Tiny%20Asian%20Casting"
2021-07-10 00:44:43,552 (cd4) :  ERROR (logkit:22) - Traceback (most recent call last):
  File "C:\Plex\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 100, in search
    provider.search(results, lang, siteNum, search)
  File "C:\Plex\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkAdultEmpireCash.py", line 9, in search
    titleNoFormatting = searchResult.xpath('.//a[@class="grid-item-title"]/text()')[0]
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ebb5fe9f3\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
```

**Comment by hrmieon31** [comment]
> 
> 
> As I mentioned over in the following issue: #1331
> 
> AdultEmpireCash made some slight design changes so afaik all sites under that umbrella are broken. On top of that JaysPOV has additional differences from other sites on that network.
> 
> ```
> 2021-07-10 00:44:42,585 (cd4) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** JaysPOV Petite Yumi Sin Tiny Asian Casting
> 2021-07-10 00:44:42,585 (cd4) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: JaysPOV Petite Yumi Sin Tiny Asian Casting
> 2021-07-10 00:44:42,585 (cd4) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: JaysPOV Petite Yumi Sin Tiny Asian Casting
> 2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - ^^^^^^^ siteNum: 815
> 2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
> 2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - Search Title (before date processing): Petite Yumi Sin Tiny Asian Casting
> 2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - {'siteName': 'jayspov', 'searchDate': None, 'siteNum': 815, 'searchTitle': 'Petite Yumi Sin Tiny Asian Casting'}
> 2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - SearchData.title: Petite Yumi Sin Tiny Asian Casting
> 2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - SearchData.filename: JaysPOV - Petite Yumi Sin Tiny Asian Casting
> 2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - Provider: networkAdultEmpireCash
> 2021-07-10 00:44:42,592 (cd4) :  INFO (logkit:16) - Requesting GET "https://jayspov.net/MemberSceneSearch?q=Petite%20Yumi%20Sin%20Tiny%20Asian%20Casting"
> 2021-07-10 00:44:43,552 (cd4) :  ERROR (logkit:22) - Traceback (most recent call last):
>   File "C:\Plex\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 100, in search
>     provider.search(results, lang, siteNum, search)
>   File "C:\Plex\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkAdultEmpireCash.py", line 9, in search
>     titleNoFormatting = searchResult.xpath('.//a[@class="grid-item-title"]/text()')[0]
>   File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ebb5fe9f3\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
>     _getitem_           = lambda x, y: x.__getitem__(y),
> IndexError: list index out of range
> ```

Then now the agent doesnt work with all AdultEmpireCash Videos?
