### ISSUE TITLE
Kink.com not matching

### ISSUE THREAD

**Issue by timmehtimtims** [PAhelper/PhoenixAdult.bundle#1355]
Some channels have matched but others (eg: upper floor) are not working at all.

```2021-08-10 17:12:54,522 (7fee902a2b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo3NWU4ZGQwZDYzOWFmODE4czE3Cm9wZW5TdWJ0aXRsZXNIYXNoczQ5ClRoZXVwcGVyZmxvb3IgMTcgMDEgMTAgRW1tYSBIYWl6ZSBhbmQgQ2hlcnJ5IFRvcm5zNApuYW1lczIwNwolMkZtbnQlMkZ1bmlvbmZzJTJGeG1vdmllcyUyRlVwcGVyJTIwRmxvb3IlMkZUaGVVcHBlckZsb29yJTJFMTclMkUwMSUyRTEwJTJFRW1tYSUyRUhhaXplJTJFQW5kJTJFQ2hlcnJ5JTJFVG9ybiUyRVhYWCUyRTcyMHAlMkVNUDQtS1RSJTJGdGhldXBwZXJmbG9vciUyRTE3JTJFMDElMkUxMCUyRWVtbWElMkVoYWl6ZSUyRWFuZCUyRWNoZXJyeSUyRXRvcm4lMkVtcDRzOApmaWxlbmFtZXM0MAo0ODE3ZDQyYzhhYWY1ZDEyMWRiYTNiYjJiZDU0MWVkNGRjNWFlYTNkczgKcGxleEhhc2hzMgotMXM4CmR1cmF0aW9uczYKMzQ2NzIxczIKaWRyMAo_
2021-08-10 17:12:54,523 (7fee902a2b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-08-10 17:12:54,524 (7fee902a2b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo3NWU4ZGQwZDYzOWFmODE4czE3Cm9wZW5TdWJ0aXRsZXNIYXNoczQ5ClRoZXVwcGVyZmxvb3IgMTcgMDEgMTAgRW1tYSBIYWl6ZSBhbmQgQ2hlcnJ5IFRvcm5zNApuYW1lczIwNwolMkZtbnQlMkZ1bmlvbmZzJTJGeG1vdmllcyUyRlVwcGVyJTIwRmxvb3IlMkZUaGVVcHBlckZsb29yJTJFMTclMkUwMSUyRTEwJTJFRW1tYSUyRUhhaXplJTJFQW5kJTJFQ2hlcnJ5JTJFVG9ybiUyRVhYWCUyRTcyMHAlMkVNUDQtS1RSJTJGdGhldXBwZXJmbG9vciUyRTE3JTJFMDElMkUxMCUyRWVtbWElMkVoYWl6ZSUyRWFuZCUyRWNoZXJyeSUyRXRvcm4lMkVtcDRzOApmaWxlbmFtZXM0MAo0ODE3ZDQyYzhhYWY1ZDEyMWRiYTNiYjJiZDU0MWVkNGRjNWFlYTNkczgKcGxleEhhc2hzMgotMXM4CmR1cmF0aW9uczYKMzQ2NzIxczIKaWRyMAo_
2021-08-10 17:12:54,524 (7fee902a2b38) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': '75e8dd0d639af818', 'name': 'Theupperfloor 17 01 10 Emma Haize and Cherry Torn', 'filename': '%2Fmnt%2Funionfs%2Fxmovies%2FUpper%20Floor%2FTheUpperFloor%2E17%2E01%2E10%2EEmma%2EHaize%2EAnd%2ECherry%2ETorn%2EXXX%2E720p%2EMP4-KTR%2Ftheupperfloor%2E17%2E01%2E10%2Eemma%2Ehaize%2Eand%2Echerry%2Etorn%2Emp4', 'plexHash': '4817d42c8aaf5d121dba3bb2bd541ed4dc5aea3d', 'duration': '-1', 'id': '346721'}
2021-08-10 17:12:54,524 (7fee902a2b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/346721/tree'
2021-08-10 17:12:54,530 (7fee902a2b38) :  INFO (__init__:59) - ***MEDIA TITLE [from media.name]*** Theupperfloor 17 01 10 Emma Haize and Cherry Torn
2021-08-10 17:12:54,530 (7fee902a2b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Theupperfloor 17 01 10 Emma Haize and Cherry Torn
2021-08-10 17:12:54,541 (7fee902a2b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Theupperfloor 17 01 10 Emma Haize and Cherry Torn
2021-08-10 17:12:54,546 (7fee902a2b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 502
2021-08-10 17:12:54,546 (7fee902a2b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2021-08-10 17:12:54,547 (7fee902a2b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): 17 01 10 Emma Haize and Cherry Torn
2021-08-10 17:12:54,548 (7fee902a2b38) :  INFO (__init__:61) - {'siteName': 'theupperfloor', 'searchDate': '2017-01-10', 'siteNum': 502, 'searchTitle': 'Emma Haize and Cherry Torn'}
2021-08-10 17:12:54,548 (7fee902a2b38) :  INFO (PAsearchData:23) - SearchData.title: Emma Haize and Cherry Torn
2021-08-10 17:12:54,548 (7fee902a2b38) :  INFO (PAsearchData:26) - SearchData.date: 2017-01-10
2021-08-10 17:12:54,548 (7fee902a2b38) :  INFO (PAsearchData:29) - SearchData.filename: theupperfloor.17.01.10.emma.haize.and.cherry.torn
2021-08-10 17:12:54,548 (7fee902a2b38) :  INFO (__init__:98) - Provider: networkKink
2021-08-10 17:12:54,549 (7fee902a2b38) :  INFO (PAutils:182) - Requesting GET "http://www.kink.com/search?channelIds=theupperfloor&q=Emma%20Haize%20and%20Cherry%20Torn"
2021-08-10 17:12:54,598 (7fee902a2b38) :  INFO (PAutils:130) - FlareSolverr
2021-08-10 17:12:54,600 (7fee902a2b38) :  INFO (PAutils:182) - Requesting POST "http://localhost:8191/v1"
2021-08-10 17:12:54,602 (7fee902a2b38) :  INFO (PAutils:137) - CloudScraper
2021-08-10 17:12:54,677 (7fee902a2b38) :  INFO (PAutils:144) - ReqBin
2021-08-10 17:12:54,679 (7fee902a2b38) :  INFO (PAutils:182) - Requesting POST "https://api.reqbin.com/api/v1/requests"
2021-08-10 17:12:55,071 (7fee8ec43b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjM0NTgwNXMyCmlkczYwCls5ODMwXSBDaGVycnkgVG9ybicgcyBhbmFsIGRheSEgW1RoZSBVcHBlciBGbG9vcl0gMjAxMC0xMC0wMXM0Cm5hbWVuczQKeWVhcnIwCg__
2021-08-10 17:12:55,072 (7fee8ec43b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-08-10 17:12:55,073 (7fee8ec43b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjM0NTgwNXMyCmlkczYwCls5ODMwXSBDaGVycnkgVG9ybicgcyBhbmFsIGRheSEgW1RoZSBVcHBlciBGbG9vcl0gMjAxMC0xMC0wMXM0Cm5hbWVuczQKeWVhcnIwCg__
2021-08-10 17:12:55,074 (7fee8ec43b38) :  INFO (agentkit:961) - Searching for matches for {'year': None, 'id': '345805', 'name': "[9830] Cherry Torn' s anal day! [The Upper Floor] 2010-10-01"}
2021-08-10 17:12:55,074 (7fee8ec43b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/345805/tree'
2021-08-10 17:12:55,081 (7fee8ec43b38) :  INFO (__init__:59) - ***MEDIA TITLE [from media.name]*** [9830] Cherry Torn' s anal day! [The Upper Floor] 2010-10-01
2021-08-10 17:12:55,081 (7fee8ec43b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: [9830] Cherry Torn' s anal day! [The Upper Floor] 2010-10-01
2021-08-10 17:12:55,093 (7fee8ec43b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: [9830] Cherry Torn' s anal day! [The Upper Floor] 2010-10-01
2021-08-10 17:12:55,099 (7fee8ec43b38) :  INFO (__init__:61) - {'siteName': None, 'searchDate': None, 'siteNum': None, 'searchTitle': None}
2021-08-10 17:12:55,099 (7fee8ec43b38) :  INFO (PAsearchData:23) - SearchData.title: [9830] Cherry Torn' s anal day! [The Upper Floor] 2010-10-01
2021-08-10 17:12:55,100 (7fee8ec43b38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-08-10 17:12:55,100 (7fee8ec43b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2021-08-10 17:12:55,145 (7fee902a2b38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-08-10 17:12:55,145 (7fee902a2b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2021-08-10 17:12:56,345 (7fee902a2b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgplOGJiYWFkZjNlYjQzY2Q0czE3Cm9wZW5TdWJ0aXRsZXNIYXNoczUwClRoZXVwcGVyZmxvb3IgMTcgMDEgMjQgQW5uYSBUeWxlciBhbmQgVmVydWNhIEphbWVzczQKbmFtZXMyMDkKJTJGbW50JTJGdW5pb25mcyUyRnhtb3ZpZXMlMkZVcHBlciUyMEZsb29yJTJGVGhlVXBwZXJGbG9vciUyRTE3JTJFMDElMkUyNCUyRUFubmElMkVUeWxlciUyRUFuZCUyRVZlcnVjYSUyRUphbWVzJTJFWFhYJTJFNzIwcCUyRU1QNC1LVFIlMkZ0aGV1cHBlcmZsb29yJTJFMTclMkUwMSUyRTI0JTJFYW5uYSUyRXR5bGVyJTJFYW5kJTJFdmVydWNhJTJFamFtZXMlMkVtcDRzOApmaWxlbmFtZXM0MAo2YTMwMGU5MGRjODQ5M2VlYWE1ZjVlNTVkNTU5NDFjMzQ0ODExZjk4czgKcGxleEhhc2hzMgotMXM4CmR1cmF0aW9uczYKMzQ2NzIyczIKaWRyMAo_
2021-08-10 17:12:56,346 (7fee902a2b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-08-10 17:12:56,346 (7fee902a2b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgplOGJiYWFkZjNlYjQzY2Q0czE3Cm9wZW5TdWJ0aXRsZXNIYXNoczUwClRoZXVwcGVyZmxvb3IgMTcgMDEgMjQgQW5uYSBUeWxlciBhbmQgVmVydWNhIEphbWVzczQKbmFtZXMyMDkKJTJGbW50JTJGdW5pb25mcyUyRnhtb3ZpZXMlMkZVcHBlciUyMEZsb29yJTJGVGhlVXBwZXJGbG9vciUyRTE3JTJFMDElMkUyNCUyRUFubmElMkVUeWxlciUyRUFuZCUyRVZlcnVjYSUyRUphbWVzJTJFWFhYJTJFNzIwcCUyRU1QNC1LVFIlMkZ0aGV1cHBlcmZsb29yJTJFMTclMkUwMSUyRTI0JTJFYW5uYSUyRXR5bGVyJTJFYW5kJTJFdmVydWNhJTJFamFtZXMlMkVtcDRzOApmaWxlbmFtZXM0MAo2YTMwMGU5MGRjODQ5M2VlYWE1ZjVlNTVkNTU5NDFjMzQ0ODExZjk4czgKcGxleEhhc2hzMgotMXM4CmR1cmF0aW9uczYKMzQ2NzIyczIKaWRyMAo_
2021-08-10 17:12:56,347 (7fee902a2b38) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': 'e8bbaadf3eb43cd4', 'name': 'Theupperfloor 17 01 24 Anna Tyler and Veruca James', 'filename': '%2Fmnt%2Funionfs%2Fxmovies%2FUpper%20Floor%2FTheUpperFloor%2E17%2E01%2E24%2EAnna%2ETyler%2EAnd%2EVeruca%2EJames%2EXXX%2E720p%2EMP4-KTR%2Ftheupperfloor%2E17%2E01%2E24%2Eanna%2Etyler%2Eand%2Everuca%2Ejames%2Emp4', 'plexHash': '6a300e90dc8493eeaa5f5e55d55941c344811f98', 'duration': '-1', 'id': '346722'}
2021-08-10 17:12:56,347 (7fee902a2b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/346722/tree'
2021-08-10 17:12:56,352 (7fee902a2b38) :  INFO (__init__:59) - ***MEDIA TITLE [from media.name]*** Theupperfloor 17 01 24 Anna Tyler and Veruca James
2021-08-10 17:12:56,353 (7fee902a2b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Theupperfloor 17 01 24 Anna Tyler and Veruca James
2021-08-10 17:12:56,362 (7fee902a2b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Theupperfloor 17 01 24 Anna Tyler and Veruca James
2021-08-10 17:12:56,367 (7fee902a2b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 502
2021-08-10 17:12:56,367 (7fee902a2b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2021-08-10 17:12:56,369 (7fee902a2b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): 17 01 24 Anna Tyler and Veruca James
2021-08-10 17:12:56,369 (7fee902a2b38) :  INFO (__init__:61) - {'siteName': 'theupperfloor', 'searchDate': '2017-01-24', 'siteNum': 502, 'searchTitle': 'Anna Tyler and Veruca James'}
2021-08-10 17:12:56,369 (7fee902a2b38) :  INFO (PAsearchData:23) - SearchData.title: Anna Tyler and Veruca James
2021-08-10 17:12:56,369 (7fee902a2b38) :  INFO (PAsearchData:26) - SearchData.date: 2017-01-24
2021-08-10 17:12:56,369 (7fee902a2b38) :  INFO (PAsearchData:29) - SearchData.filename: theupperfloor.17.01.24.anna.tyler.and.veruca.james
2021-08-10 17:12:56,370 (7fee902a2b38) :  INFO (__init__:98) - Provider: networkKink
2021-08-10 17:12:56,371 (7fee902a2b38) :  INFO (PAutils:182) - Requesting GET "http://www.kink.com/search?channelIds=theupperfloor&q=Anna%20Tyler%20and%20Veruca%20James"
2021-08-10 17:12:56,419 (7fee902a2b38) :  INFO (PAutils:130) - FlareSolverr
2021-08-10 17:12:56,421 (7fee902a2b38) :  INFO (PAutils:182) - Requesting POST "http://localhost:8191/v1"
2021-08-10 17:12:56,423 (7fee902a2b38) :  INFO (PAutils:137) - CloudScraper
2021-08-10 17:12:56,487 (7fee902a2b38) :  INFO (PAutils:144) - ReqBin
2021-08-10 17:12:56,489 (7fee902a2b38) :  INFO (PAutils:182) - Requesting POST "https://api.reqbin.com/api/v1/requests"
2021-08-10 17:12:56,976 (7fee902a2b38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-08-10 17:12:56,977 (7fee902a2b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2021-08-10 17:13:02,970 (7fee902a2b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjM0NTgwNXMyCmlkczExCmtpbmsgWzk4MzBdczQKbmFtZW5zNAp5ZWFycjAK
2021-08-10 17:13:02,970 (7fee902a2b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-08-10 17:13:02,971 (7fee902a2b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjM0NTgwNXMyCmlkczExCmtpbmsgWzk4MzBdczQKbmFtZW5zNAp5ZWFycjAK
2021-08-10 17:13:02,971 (7fee902a2b38) :  INFO (agentkit:961) - Searching for matches for {'year': None, 'id': '345805', 'name': 'kink [9830]'}
2021-08-10 17:13:02,971 (7fee902a2b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/345805/tree'
2021-08-10 17:13:02,980 (7fee902a2b38) :  INFO (__init__:59) - ***MEDIA TITLE [from media.name]*** kink [9830]
2021-08-10 17:13:02,980 (7fee902a2b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: kink [9830]
2021-08-10 17:13:02,991 (7fee902a2b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: kink [9830]
2021-08-10 17:13:02,998 (7fee902a2b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 490
2021-08-10 17:13:02,998 (7fee902a2b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2021-08-10 17:13:03,000 (7fee902a2b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): 9830
2021-08-10 17:13:03,000 (7fee902a2b38) :  INFO (__init__:61) - {'siteName': 'kink', 'searchDate': None, 'siteNum': 490, 'searchTitle': '9830'}
2021-08-10 17:13:03,001 (7fee902a2b38) :  INFO (PAsearchData:23) - SearchData.title: 9830
2021-08-10 17:13:03,001 (7fee902a2b38) :  INFO (__init__:98) - Provider: networkKink
2021-08-10 17:13:03,002 (7fee902a2b38) :  INFO (PAutils:182) - Requesting GET "http://www.kink.com/shoot/9830"
2021-08-10 17:13:03,064 (7fee902a2b38) :  INFO (PAutils:130) - FlareSolverr
2021-08-10 17:13:03,066 (7fee902a2b38) :  INFO (PAutils:182) - Requesting POST "http://localhost:8191/v1"
2021-08-10 17:13:03,068 (7fee902a2b38) :  INFO (PAutils:137) - CloudScraper
2021-08-10 17:13:03,141 (7fee902a2b38) :  INFO (PAutils:144) - ReqBin
2021-08-10 17:13:03,143 (7fee902a2b38) :  INFO (PAutils:182) - Requesting POST "https://api.reqbin.com/api/v1/requests"
2021-08-10 17:13:03,621 (7fee902a2b38) :  ERROR (__init__:102) - Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 100, in search
    provider.search(results, lang, siteNum, search)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkKink.py", line 33, in search
    score = 100 - Util.LevenshteinDistance(searchData.date, releaseDate)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-e2e58f321/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2021-08-10 17:13:03,622 (7fee902a2b38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-08-10 17:13:03,622 (7fee902a2b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
```

**Comment by timmehtimtims** [comment]
Further to this, I tried using stash and I got a 403 error. So I'm assuming that trying to match my Plex library files with phoenixadult has got me a ban of some kind. Would that be a reasonable assumption? 
If that suspicion is correct, do we have any idea whether these bans are temporary or permanent? I've never had one before, certainly not with kink.

**Comment by timmehtimtims** [comment]
A little more information from anyone else who'd experienced this same thing:
https://kink.zendesk.com/hc/en-us/articles/360041640993-Kink-com-IP-Block-Information
