### ISSUE TITLE
TrueAnal Matching Issue

### ISSUE THREAD

**Issue by Dranzer94** [PAhelper/PhoenixAdult.bundle#1362]
It seems like there's a problem with the exact matching for trueanal.com, the log indicates "IndexError: list index out of range"

See attached log
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/7069392/com.plexapp.agents.phoenixadult.log)

**Comment by a18project** [comment]
> Swallowed / TrueAnal / Nymphos / AllAnal / AnalOnly | Matching type: Exact - Direct URL

Try search with this: TrueAnal 538/savannahs-anal-ride
Or rename the file to: TrueAnal-538-savannahs-anal-ride

**Comment by Dranzer94** [comment]
Tried it, get the same error
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/7108293/com.plexapp.agents.phoenixadult.log)

**Comment by a18project** [comment]
Works fine on my end. Probably network related.

**Comment by DallanInvictus** [comment]
I'm actually getting a similar error on Nympho, which isn't using the number portion. Here's the relevant log portion:

2021-09-06 08:18:02,430 (4080) :  INFO (agentkit:961) - Searching for matches for {'year': None, 'id': '26543', 'name': 'Nympho skylars-fucking-frenzy'}
2021-09-06 08:18:02,430 (4080) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/26543/tree'
2021-09-06 08:18:02,437 (4080) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** Nympho skylars-fucking-frenzy
2021-09-06 08:18:02,437 (4080) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Nympho skylars-fucking-frenzy
2021-09-06 08:18:02,447 (4080) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Nympho skylars-fucking-frenzy
2021-09-06 08:18:02,453 (4080) :  INFO (logkit:16) - ^^^^^^^ siteNum: 284
2021-09-06 08:18:02,453 (4080) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2021-09-06 08:18:02,456 (4080) :  INFO (logkit:16) - Search Title (before date processing): Skylars Fucking Frenzy
2021-09-06 08:18:02,456 (4080) :  INFO (logkit:16) - {'siteName': 'nympho', 'searchDate': None, 'siteNum': 284, 'searchTitle': 'Skylars Fucking Frenzy'}
2021-09-06 08:18:02,456 (4080) :  INFO (logkit:16) - SearchData.title: Skylars Fucking Frenzy
2021-09-06 08:18:02,457 (4080) :  INFO (logkit:16) - Provider: networkSteppedUp
2021-09-06 08:18:02,457 (4080) :  INFO (logkit:16) - Requesting GET "https://tour.nympho.com/view/skylars-fucking-frenzy"
2021-09-06 08:18:13,532 (4080) :  CRITICAL (core:574) - Error parsing with lxml, falling back to soupparser (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-1a38e63c6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\data.py", line 157, in from_string
    return html.fromstring(markup, parser=html_parser)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\lxml\html\__init__.py", line 634, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\lxml\html\__init__.py", line 535, in document_fromstring
    "Document is empty")
ParserError: Document is empty

2021-09-06 08:18:13,532 (4080) :  ERROR (logkit:22) - Traceback (most recent call last):
  File "D:\ProgramData\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 100, in search
    provider.search(results, lang, siteNum, search)
  File "D:\ProgramData\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkSteppedUp.py", line 15, in search
    titleNoFormatting = detailsPageElements.xpath('//h1[@class="title"] | //h2[@class="title"]')[0].text_content().strip()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-1a38e63c6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
`

**Comment by a18project** [comment]
> ParserError: Document is empty
Highly likely it is a network related problem. Unable to reproduce error here.

**Comment by c1ockwork** [comment]
I'm receiving this error as well.  I note I get a security check when visit the site for the first time - maybe this is the page that's being returned to the scraper?

![Screenshot 2021-09-25 201604](https://user-images.githubusercontent.com/50071549/134767974-da56d717-108c-47f2-a8d5-0b5b9f57480b.jpg)

**Comment by Marty69420** [comment]
I am having the same issue with Swallowed / TrueAnal / Nymphos / AllAnal / AnalOnly
I just tried moving files that auto-matched in the past (15. June 2021) and they no longer match. 

Two examples:
TrueAnal - 2020.11.20 - 662 siri-takes-it-all
Nymphos - 2021.03.08 - violet-brings-the-bounce

Tried on two separate servers, with the exact same results

**Comment by a18project** [comment]
Looks like same problem as #951 
No solution so far.
