### ISSUE TITLE
Watch4Beauty matching Issues

### ISSUE THREAD

**Issue by Chodbin** [PAhelper/PhoenixAdult.bundle#1373]
**Describe the bug**
Getting no matches for a lot of scenes from W4B, for example;

**Include**
1. Scene URL
https://www.watch4beauty.com/updates/dark-angel
2. File Name
Watch4Beauty - 2006-01-11 - Veronica Da Souza Dark Angel
3. Log File
`2021-09-09 02:53:43,176 (6fe4) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-09-09 02:53:43,176 (6fe4) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2021-09-09 02:53:53,519 (b254) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1Cjk5OTAwczIKaWRzNTYKV2F0Y2g0QmVhdXR5IC0gMjAwNi0wMS0xMSAtIFZlcm9uaWNhIERhIFNvdXphIERhcmsgQW5nZWxzNApuYW1lczQKMjAwNnM0CnllYXJyMAo_
2021-09-09 02:53:53,520 (b254) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-09-09 02:53:53,522 (b254) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM1Cjk5OTAwczIKaWRzNTYKV2F0Y2g0QmVhdXR5IC0gMjAwNi0wMS0xMSAtIFZlcm9uaWNhIERhIFNvdXphIERhcmsgQW5nZWxzNApuYW1lczQKMjAwNnM0CnllYXJyMAo_
2021-09-09 02:53:53,523 (b254) :  INFO (agentkit:961) - Searching for matches for {'year': '2006', 'id': '99900', 'name': 'Watch4Beauty - 2006-01-11 - Veronica Da Souza Dark Angel'}
2021-09-09 02:53:53,523 (b254) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/99900/tree'
2021-09-09 02:53:53,536 (b254) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** Watch4Beauty - 2006-01-11 - Veronica Da Souza Dark Angel
2021-09-09 02:53:53,536 (b254) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Watch4Beauty - 2006-01-11 - Veronica Da Souza Dark Angel
2021-09-09 02:53:53,543 (b254) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Watch4Beauty - 2006-01-11 - Veronica Da Souza Dark Angel
2021-09-09 02:53:53,551 (b254) :  INFO (logkit:16) - ^^^^^^^ siteNum: 1185
2021-09-09 02:53:53,551 (b254) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2021-09-09 02:53:53,552 (b254) :  INFO (logkit:16) - Search Title (before date processing): 2006 01 11 Veronica Da Souza Dark Angel
2021-09-09 02:53:53,552 (b254) :  INFO (logkit:16) - {'siteName': 'watch4beauty', 'searchDate': '2006-01-11', 'siteNum': 1185, 'searchTitle': 'Veronica Da Souza Dark Angel'}
2021-09-09 02:53:53,552 (b254) :  INFO (logkit:16) - SearchData.title: Veronica Da Souza Dark Angel
2021-09-09 02:53:53,552 (b254) :  INFO (logkit:16) - SearchData.date: 2006-01-11
2021-09-09 02:53:53,553 (b254) :  INFO (logkit:16) - Provider: siteWatch4Beauty
2021-09-09 02:53:53,555 (b254) :  INFO (logkit:16) - Requesting GET "https://www.watch4beauty.com/api/3yAjOB66l2A566U/veronica-da-souza/updates"
2021-09-09 02:53:54,119 (b254) :  ERROR (logkit:22) - Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 100, in search
    provider.search(results, lang, siteNum, search)
  File "C:\Users\XXX\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\siteWatch4Beauty.py", line 59, in search
    results.Append(MetadataSearchResult(id='%s|%d|%s' % (modelString, siteNum, sceneString), name='%s, %s [Watch4Beauty]' % (sceneName, sceneDateString), score=score, lang=lang))
  File "C:\Users\XXX\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\scanner.py", line 122, in scan_once
    return _scan_once(string, idx)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\scanner.py", line 118, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2021-09-09 02:53:54,121 (b254) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-09-09 02:53:54,121 (b254) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes`

**Comment by cristiano1976pt** [comment]
Hello. I have the same issue. Over 10 Files since Weeks where i get no match or something.
