### ISSUE TITLE
Cannot Match Scenes with Data18

### ISSUE THREAD

**Issue by Spanishu** [PAhelper/PhoenixAdult.bundle#1436]
I have updated the plugin to the latest version. I have been trying to match a data18.com scene
What I did 
entered in the searchfield data18scenes 1265984
It does not result a match. How do I match scenes now in this new plugin?

`2021-12-27 10:01:43,058 (-4c2b4288) :  INFO (__init__:111) - Provider: networkMetadataAPI
2021-12-27 10:01:43,066 (-4c2b4288) :  INFO (PAutils:182) - Requesting GET "https://api.metadataapi.net/scenes?parse=Maddy%20May%20and%20Lily%20Lou&has$
2021-12-27 10:01:44,111 (-4c2b4288) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-12-27 10:01:44,113 (-4c2b4288) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2021-12-27 10:01:48,213 (-4c2b4288) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW5$
2021-12-27 10:01:48,216 (-4c2b4288) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-12-27 10:01:48,220 (-4c2b4288) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW5$
2021-12-27 10:01:48,221 (-4c2b4288) :  INFO (agentkit:961) - Searching for matches for {'year': None, 'id': '26811', 'name': 'Data18Scenes 1265984'}
2021-12-27 10:01:48,223 (-4c2b4288) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/26811/tree'
2021-12-27 10:01:48,253 (-4c2b4288) :  INFO (__init__:60) - ***MEDIA TITLE [from media.name]*** Data18Scenes 1265984
2021-12-27 10:01:48,254 (-4c2b4288) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Data18Scenes 1265984
2021-12-27 10:01:48,301 (-4c2b4288) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Data18Scenes 1265984
2021-12-27 10:01:48,334 (-4c2b4288) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 1071
2021-12-27 10:01:48,335 (-4c2b4288) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2021-12-27 10:01:48,345 (-4c2b4288) :  INFO (PAsearchSites:96) - Search Title (before date processing): 1265984
2021-12-27 10:01:48,347 (-4c2b4288) :  INFO (__init__:62) - {'siteName': 'data18scenes', 'searchDate': None, 'siteNum': 1071, 'searchTitle': '1265984'}
2021-12-27 10:01:48,348 (-4c2b4288) :  INFO (PAsearchData:23) - SearchData.title: 1265984
2021-12-27 10:01:48,349 (-4c2b4288) :  INFO (__init__:99) - Provider: siteData18Scenes
2021-12-27 10:01:48,355 (-4c2b4288) :  INFO (PAutils:182) - Requesting GET "http://www.data18.com/search/?k="
2021-12-27 10:01:48,959 (-4c2b4288) :  INFO (PAutils:182) - Requesting GET "http://www.data18.com/scenes/1265984"
2021-12-27 10:01:49,409 (-4c2b4288) :  ERROR (__init__:103) - Traceback (most recent call last):
  File "/home/pi/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 101, in search
    provider.search(results, lang, siteNum, search)
  File "/home/pi/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteData18Scenes.py", line 125, in search
    score = 80 - Util.LevenshteinDistance(searchData.date, releaseDate)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/dateutil/parser.py", line $
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-c43dc0277/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/dateutil/parser.py", line $
    raise ValueError, "unknown string format"
ValueError: unknown string format

2021-12-27 10:01:49,431 (-4c2b4288) :  INFO (__init__:111) - Provider: networkMetadataAPI
2021-12-27 10:01:49,436 (-4c2b4288) :  INFO (PAutils:182) - Requesting GET "https://api.metadataapi.net/scenes?parse="
2021-12-27 10:01:50,380 (-4c2b4288) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2021-12-27 10:01:50,381 (-4c2b4288) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes

`

**Comment by drraymond27** [comment]
Well, I tried to add the new version of Data18, but don't working, something missing that I don't look , so I left to the experts the fix .

**Comment by ConstrictM** [comment]
Has to do with the Date coming from the site. Since they changed the date extract has to be updated

Line 112 date = detailsPageElements.xpath('//span[@class][./*[contains(.., "date")]]')[0].text_content().split(':', 2)[-1].strip()

Output: Date: December 11, 2021, more updates...

Shouldn't be too difficult to fix. I can fix in a bit.
