### ISSUE TITLE
TeamSkeet and Mylf: Not Finding Some Scenes

### ISSUE THREAD

**Issue by HWatBobby** [PAhelper/PhoenixAdult.bundle#1549]
**Describe the bug**
Seem to get this issue with some TeamSkeet scenes, but not all and this error only comes up with TeamSkeet and Mylf sites. Tried redownloading the plugin, but the issue continues. I get no results when matching.

**Include**
1. Scene URL
`https://www.teamskeet.com/movies/the-desire-to-improve`
2. File Name
`BadMILFs - 2022-03-19 - The Desire To Improve [Abby Somers, Bess Breast].mp4`
4. Log File
```
2022-04-06 21:02:12,257 (154a01845b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo2YmM0NWRmNzExN2Q1ZTBkczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczQxCkJhZG1pbGZzIDIwMjIgMDMgMTkgdGhlIERlc2lyZSB0byBJbXByb3ZlczQKbmFtZXMxMzMKJTJGcHJpdmF0ZSUyRkJhZCUyME1JTEZzJTJGQmFkTUlMRnMlMjAtJTIwMjAyMi0wMy0xOSUyMC0lMjBUaGUlMjBEZXNpcmUlMjBUbyUyMEltcHJvdmUlMjAlNUJBYmJ5JTIwU29tZXJzJTJDJTIwQmVzcyUyMEJyZWFzdCU1RCUyRW1wNHM4CmZpbGVuYW1lczQwCjAyYTM1Njk2YTBkZGFjMmMwNTEwYzY0MTJmMjUwM2M1NDc3ODc4MzNzOApwbGV4SGFzaHM3CjMxODM3MTBzOApkdXJhdGlvbnM2CjEyMDM2M3MyCmlkcjAK
2022-04-06 21:02:12,259 (154a01845b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2022-04-06 21:02:12,262 (154a01845b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgo2YmM0NWRmNzExN2Q1ZTBkczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczQxCkJhZG1pbGZzIDIwMjIgMDMgMTkgdGhlIERlc2lyZSB0byBJbXByb3ZlczQKbmFtZXMxMzMKJTJGcHJpdmF0ZSUyRkJhZCUyME1JTEZzJTJGQmFkTUlMRnMlMjAtJTIwMjAyMi0wMy0xOSUyMC0lMjBUaGUlMjBEZXNpcmUlMjBUbyUyMEltcHJvdmUlMjAlNUJBYmJ5JTIwU29tZXJzJTJDJTIwQmVzcyUyMEJyZWFzdCU1RCUyRW1wNHM4CmZpbGVuYW1lczQwCjAyYTM1Njk2YTBkZGFjMmMwNTEwYzY0MTJmMjUwM2M1NDc3ODc4MzNzOApwbGV4SGFzaHM3CjMxODM3MTBzOApkdXJhdGlvbnM2CjEyMDM2M3MyCmlkcjAK
2022-04-06 21:02:12,262 (154a01845b38) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': '6bc45df7117d5e0d', 'name': 'Badmilfs 2022 03 19 the Desire to Improve', 'filename': '%2Fprivate%2FBad%20MILFs%2FBadMILFs%20-%202022-03-19%20-%20The%20Desire%20To%20Improve%20%5BAbby%20Somers%2C%20Bess%20Breast%5D%2Emp4', 'plexHash': '02a35696a0ddac2c0510c6412f2503c547787833', 'duration': '3183710', 'id': '120363'}
2022-04-06 21:02:12,263 (154a01845b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/120363/tree'
2022-04-06 21:02:12,275 (154a01845b38) :  INFO (__init__:61) - ***MEDIA TITLE [from media.name]*** Badmilfs 2022 03 19 the Desire to Improve
2022-04-06 21:02:12,276 (154a01845b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Badmilfs 2022 03 19 the Desire to Improve
2022-04-06 21:02:12,291 (154a01845b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Badmilfs 2022 03 19 the Desire to Improve
2022-04-06 21:02:12,304 (154a01845b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 211
2022-04-06 21:02:12,304 (154a01845b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2022-04-06 21:02:12,308 (154a01845b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): 2022 03 19 the Desire to Improve
2022-04-06 21:02:12,315 (154a01845b38) :  INFO (__init__:63) - {'siteName': 'badmilfs', 'searchDate': '2022-03-19', 'siteNum': 211, 'searchTitle': 'The Desire to Improve'}
2022-04-06 21:02:12,316 (154a01845b38) :  INFO (PAsearchData:23) - SearchData.title: The Desire to Improve
2022-04-06 21:02:12,316 (154a01845b38) :  INFO (PAsearchData:26) - SearchData.date: 2022-03-19
2022-04-06 21:02:12,316 (154a01845b38) :  INFO (PAsearchData:29) - SearchData.filename: BadMILFs - 2022-03-19 - The Desire To Improve [Abby Somers, Bess Breast]
2022-04-06 21:02:12,317 (154a01845b38) :  INFO (__init__:100) - Provider: networkTeamSkeet
2022-04-06 21:02:12,317 (154a01845b38) :  INFO (PAutils:225) - Using Google Search "site:teamskeet.com The Desire to Improve"
2022-04-06 21:02:15,665 (154a01845b38) :  INFO (PAutils:182) - Requesting GET "https://www.teamskeet.com"
2022-04-06 21:02:17,158 (154a01845b38) :  INFO (PAutils:182) - Requesting GET "https://store2.psmcdn.net/ts-elastic-d5cat0jl5o-videoscontent/_search?q=the-desire-to-improve"
2022-04-06 21:02:17,220 (154a01845b38) :  INFO (PAutils:130) - FlareSolverr
2022-04-06 21:02:17,222 (154a01845b38) :  INFO (PAutils:182) - Requesting POST "http://localhost:8191/v1"
2022-04-06 21:02:17,225 (154a01845b38) :  INFO (PAutils:137) - CloudScraper
2022-04-06 21:02:17,323 (154a01845b38) :  INFO (PAutils:144) - ReqBin
2022-04-06 21:02:17,325 (154a01845b38) :  INFO (PAutils:182) - Requesting POST "https://api.reqbin.com/api/v1/requests"
2022-04-06 21:02:17,515 (154a01845b38) :  ERROR (__init__:104) - Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 102, in search
    provider.search(results, lang, siteNum, search)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkTeamSkeet.py", line 54, in search
    detailsPageElements = getDataFromAPI(dbURL, sceneType, sceneName, siteNum)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkTeamSkeet.py", line 24, in getDataFromAPI
    data = data.json()
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Libraries/Shared/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2022-04-06 21:02:17,517 (154a01845b38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2022-04-06 21:02:17,517 (154a01845b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
```

**Comment by drraymond27** [comment]
same here 
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/8456171/com.plexapp.agents.phoenixadult.log)
