### ISSUE TITLE
Tonight's Girlfriend not matching?

### ISSUE THREAD

**Issue by refractive2** [PAhelper/PhoenixAdult.bundle#1562]
Tonight's Girlfriend matching doesn't seem to be working – I'm trying Ann Marie Rios' scene and haven't been able to match to it, and I've tried other actresses' names just as tests and they don't seem to be working for me either.

1. Scene URL: https://www.tonightsgirlfriend.com/scene/ann-marie-rios-13063
2. File Name: `Tonight's Girlfriend - Ann Marie Rios.mp4`
3. Log File:

```
2022-05-09 23:29:02,835 (7efea5d32b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgphZjI2MGJhM2I5NDA3YzIzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczM1ClRvbmlnaHQncyBHaXJsZnJpZW5kIEFubiBNYXJpZSBSaW9zczQKbmFtZXMxMDQKJTJGdm9sdW1lMSUyRk1vdmllcyUyRlBvcm4lMkZOYXVnaHR5JTIwQW1lcmljYSUyRlRvbmlnaHQlMjdzJTIwR2lybGZyaWVuZCUyMC0lMjBBbm4lMjBNYXJpZSUyMFJpb3MlMkVtcDRzOApmaWxlbmFtZXM0MApmNDViYWFlZDIxNDVmNDEwNDZlNWEzMmJhN2I1OTFhMGViNjZiOTNjczgKcGxleEhhc2hzMgotMXM4CmR1cmF0aW9uczQKODY2NHMyCmlkcjAK
2022-05-09 23:29:02,837 (7efea5d32b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2022-05-09 23:29:02,840 (7efea5d32b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgphZjI2MGJhM2I5NDA3YzIzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczM1ClRvbmlnaHQncyBHaXJsZnJpZW5kIEFubiBNYXJpZSBSaW9zczQKbmFtZXMxMDQKJTJGdm9sdW1lMSUyRk1vdmllcyUyRlBvcm4lMkZOYXVnaHR5JTIwQW1lcmljYSUyRlRvbmlnaHQlMjdzJTIwR2lybGZyaWVuZCUyMC0lMjBBbm4lMjBNYXJpZSUyMFJpb3MlMkVtcDRzOApmaWxlbmFtZXM0MApmNDViYWFlZDIxNDVmNDEwNDZlNWEzMmJhN2I1OTFhMGViNjZiOTNjczgKcGxleEhhc2hzMgotMXM4CmR1cmF0aW9uczQKODY2NHMyCmlkcjAK
2022-05-09 23:29:02,842 (7efea5d32b38) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': 'af260ba3b9407c23', 'name': "Tonight's Girlfriend Ann Marie Rios", 'filename': '%2Fvolume1%2FMovies%2FPorn%2FNaughty%20America%2FTonight%27s%20Girlfriend%20-%20Ann%20Marie%20Rios%2Emp4', 'plexHash': 'f45baaed2145f41046e5a32ba7b591a0eb66b93c', 'duration': '-1', 'id': '8664'}
2022-05-09 23:29:02,843 (7efea5d32b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/8664/tree'
2022-05-09 23:29:02,906 (7efea5d32b38) :  INFO (__init__:64) - ***MEDIA TITLE [from media.name]*** Tonight's Girlfriend Ann Marie Rios
2022-05-09 23:29:02,907 (7efea5d32b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Tonight's Girlfriend Ann Marie Rios
2022-05-09 23:29:02,944 (7efea5d32b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Tonight's Girlfriend Ann Marie Rios
2022-05-09 23:29:02,978 (7efea5d32b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 627
2022-05-09 23:29:02,979 (7efea5d32b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2022-05-09 23:29:02,986 (7efea5d32b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): Ann Marie Rios
2022-05-09 23:29:02,988 (7efea5d32b38) :  INFO (__init__:66) - {'siteName': 'tonightsgirlfriend', 'searchDate': None, 'siteNum': 627, 'searchTitle': 'Ann Marie Rios'}
2022-05-09 23:29:02,989 (7efea5d32b38) :  INFO (PAsearchData:23) - SearchData.title: Ann Marie Rios
2022-05-09 23:29:02,990 (7efea5d32b38) :  INFO (PAsearchData:29) - SearchData.filename: Tonight's Girlfriend - Ann Marie Rios
2022-05-09 23:29:02,990 (7efea5d32b38) :  INFO (__init__:103) - Provider: siteTonightsGirlfriend
2022-05-09 23:29:02,995 (7efea5d32b38) :  INFO (PAutils:182) - Requesting GET "https://www.tonightsgirlfriend.com/pornstar/ann-marie-rios/?p=1"
2022-05-09 23:29:04,678 (7efea5d32b38) :  ERROR (__init__:107) - Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 105, in search
    provider.search(results, lang, siteNum, search)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteTonightsGirlfriend.py", line 22, in search
    releaseDate = parse(searchResult.xpath('.//span[@class="available-date"]')[0].text_content().strip()).strftime('%m-%d-%y')
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-872b93b91/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2022-05-09 23:29:04,681 (7efea5d32b38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2022-05-09 23:29:04,682 (7efea5d32b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2022-05-09 23:29:04,778 (7efea5d32b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgphZjI2MGJhM2I5NDA3YzIzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczM1ClRvbmlnaHQncyBHaXJsZnJpZW5kIEFubiBNYXJpZSBSaW9zczQKbmFtZXMxMDQKJTJGdm9sdW1lMSUyRk1vdmllcyUyRlBvcm4lMkZOYXVnaHR5JTIwQW1lcmljYSUyRlRvbmlnaHQlMjdzJTIwR2lybGZyaWVuZCUyMC0lMjBBbm4lMjBNYXJpZSUyMFJpb3MlMkVtcDRzOApmaWxlbmFtZXM0MApmNDViYWFlZDIxNDVmNDEwNDZlNWEzMmJhN2I1OTFhMGViNjZiOTNjczgKcGxleEhhc2hzMgotMXM4CmR1cmF0aW9uczQKODY2NHMyCmlkcjAK
2022-05-09 23:29:04,780 (7efea5d32b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2022-05-09 23:29:04,782 (7efea5d32b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IwczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGU2CnMxNgphZjI2MGJhM2I5NDA3YzIzczE3Cm9wZW5TdWJ0aXRsZXNIYXNoczM1ClRvbmlnaHQncyBHaXJsZnJpZW5kIEFubiBNYXJpZSBSaW9zczQKbmFtZXMxMDQKJTJGdm9sdW1lMSUyRk1vdmllcyUyRlBvcm4lMkZOYXVnaHR5JTIwQW1lcmljYSUyRlRvbmlnaHQlMjdzJTIwR2lybGZyaWVuZCUyMC0lMjBBbm4lMjBNYXJpZSUyMFJpb3MlMkVtcDRzOApmaWxlbmFtZXM0MApmNDViYWFlZDIxNDVmNDEwNDZlNWEzMmJhN2I1OTFhMGViNjZiOTNjczgKcGxleEhhc2hzMgotMXM4CmR1cmF0aW9uczQKODY2NHMyCmlkcjAK
2022-05-09 23:29:04,783 (7efea5d32b38) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': 'af260ba3b9407c23', 'name': "Tonight's Girlfriend Ann Marie Rios", 'filename': '%2Fvolume1%2FMovies%2FPorn%2FNaughty%20America%2FTonight%27s%20Girlfriend%20-%20Ann%20Marie%20Rios%2Emp4', 'plexHash': 'f45baaed2145f41046e5a32ba7b591a0eb66b93c', 'duration': '-1', 'id': '8664'}
2022-05-09 23:29:04,784 (7efea5d32b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/8664/tree'
2022-05-09 23:29:04,799 (7efea5d32b38) :  INFO (__init__:64) - ***MEDIA TITLE [from media.name]*** Tonight's Girlfriend Ann Marie Rios
2022-05-09 23:29:04,800 (7efea5d32b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Tonight's Girlfriend Ann Marie Rios
2022-05-09 23:29:04,838 (7efea5d32b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Tonight's Girlfriend Ann Marie Rios
2022-05-09 23:29:04,871 (7efea5d32b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 627
2022-05-09 23:29:04,872 (7efea5d32b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2022-05-09 23:29:04,879 (7efea5d32b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): Ann Marie Rios
2022-05-09 23:29:04,881 (7efea5d32b38) :  INFO (__init__:66) - {'siteName': 'tonightsgirlfriend', 'searchDate': None, 'siteNum': 627, 'searchTitle': 'Ann Marie Rios'}
2022-05-09 23:29:04,882 (7efea5d32b38) :  INFO (PAsearchData:23) - SearchData.title: Ann Marie Rios
2022-05-09 23:29:04,883 (7efea5d32b38) :  INFO (PAsearchData:29) - SearchData.filename: Tonight's Girlfriend - Ann Marie Rios
2022-05-09 23:29:04,883 (7efea5d32b38) :  INFO (__init__:103) - Provider: siteTonightsGirlfriend
2022-05-09 23:29:04,888 (7efea5d32b38) :  INFO (PAutils:182) - Requesting GET "https://www.tonightsgirlfriend.com/pornstar/ann-marie-rios/?p=1"
2022-05-09 23:29:07,622 (7efea5d32b38) :  ERROR (__init__:107) - Traceback (most recent call last):
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 105, in search
    provider.search(results, lang, siteNum, search)
  File "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteTonightsGirlfriend.py", line 22, in search
    releaseDate = parse(searchResult.xpath('.//span[@class="available-date"]')[0].text_content().strip()).strftime('%m-%d-%y')
  File "/volume1/@appstore/Plex Media Server/Resources/Plug-ins-872b93b91/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range

2022-05-09 23:29:08,194 (7efea5d32b38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2022-05-09 23:29:08,195 (7efea5d32b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
```

**Comment by chempke** [comment]
Same problem here. 
But it looks like a site rework for me.

**Comment by refractive2** [comment]
OMG, I didn't know you could use data18 data with PhoenixAdult, that is amazing. Thanks!
