### ISSUE TITLE
BBCpie broken

### ISSUE THREAD

**Issue by idontknownl** [PAhelper/PhoenixAdult.bundle#1564]
It used to work pretty well now there is no way to make it work (It seems it also disappear from the list of compatible sites)

**Comment by captaincoitus** [comment]
Looks like BBCPie is facing a similar if not the same error parsing the XML as all NubilesPorn Network scenes: https://github.com/PAhelper/PhoenixAdult.bundle/issues/1787

BBCPie Search Criteria: 
Scene URL: https://bbcpie.com/video/creamed-skater-girl
File Title: BBCPie - 20-08-08 - Creamed Skater Girl
Logs: 
```
2023-05-20 18:18:03,896 (1530f0894b38) :  INFO (agentkit:961) - Searching for matches for {'openSubtitlesHash': 'b51bb2818911d200', 'name': 'Bbcpie 20 08 08 Creamed Skater Girl', 'filename': '%2Fpr%2Flibraries%2Fporn_channels%2FPornPros%2FBBCPie%2FBBCPie%20-%2020-08-08%20-%20Creamed%20Skater%20Girl%2FBBCPie%20-%2020-08-08%20-%20Creamed%20Skater%20Girl%2Emp4', 'plexHash': '337dfa9b1e65429fdba8920c54121bdf4aa8a3e6', 'duration': '2259669', 'id': '82445'}
2023-05-20 18:18:03,897 (1530f0894b38) :  DEBUG (networking:144) - Requesting 'http://127.0.0.1:32400/library/metadata/82445/tree'
2023-05-20 18:18:03,903 (1530f0894b38) :  DEBUG (preferences:258) - Loaded preferences from DefaultPrefs.json
2023-05-20 18:18:03,903 (1530f0894b38) :  DEBUG (preferences:178) - Loaded the user preferences for com.plexapp.agents.phoenixadult
2023-05-20 18:18:03,904 (1530f0894b38) :  INFO (__init__:68) - ***MEDIA TITLE [from media.name]*** Bbcpie 20 08 08 Creamed Skater Girl
2023-05-20 18:18:03,904 (1530f0894b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Bbcpie 20 08 08 Creamed Skater Girl
2023-05-20 18:18:03,909 (1530f0894b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Bbcpie 20 08 08 Creamed Skater Girl
2023-05-20 18:18:03,913 (1530f0894b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 844
2023-05-20 18:18:03,913 (1530f0894b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2023-05-20 18:18:03,914 (1530f0894b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): 20 08 08 Creamed Skater Girl
2023-05-20 18:18:03,918 (1530f0894b38) :  INFO (__init__:70) - {'siteName': 'bbcpie', 'searchDate': '2020-08-08', 'siteNum': 844, 'searchTitle': 'Creamed Skater Girl'}
2023-05-20 18:18:03,919 (1530f0894b38) :  INFO (PAsearchData:23) - SearchData.title: Creamed Skater Girl
2023-05-20 18:18:03,920 (1530f0894b38) :  INFO (PAsearchData:26) - SearchData.date: 2020-08-08
2023-05-20 18:18:03,920 (1530f0894b38) :  INFO (PAsearchData:29) - SearchData.filename: BBCPie - 20-08-08 - Creamed Skater Girl
2023-05-20 18:18:03,920 (1530f0894b38) :  INFO (__init__:107) - Provider: networkPornPros
2023-05-20 18:18:03,920 (1530f0894b38) :  INFO (PAutils:226) - Using Google Search "site:bbcpie.com Creamed Skater Girl"
2023-05-20 18:18:08,948 (1530f0894b38) :  INFO (PAutils:231) - Google Search Error
2023-05-20 18:18:29,263 (1530f0894b38) :  INFO (PAutils:183) - Requesting GET "https://bbcpie.com/video/creamed-skater-girl"
2023-05-20 18:18:34,278 (1530f0894b38) :  INFO (PAutils:205) - saveRequest Error
2023-05-20 18:18:34,279 (1530f0894b38) :  CRITICAL (data:159) - Error parsing with lxml, falling back to soupparser (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/data.py", line 157, in from_string
    return html.fromstring(markup, parser=html_parser)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/lxml/html/__init__.py", line 634, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/lxml/html/__init__.py", line 535, in document_fromstring
    "Document is empty")
ParserError: Document is empty

2023-05-20 18:18:34,281 (1530f0894b38) :  ERROR (__init__:111) - Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 109, in search
    provider.search(results, lang, siteNum, search)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkPornPros.py", line 33, in search
    titleNoFormatting = PAutils.parseTitle(detailsPageElements.xpath('//h1')[0].text_content().strip(), siteNum)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
```
#### Full logs file: [com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/11523297/com.plexapp.agents.phoenixadult.log)
