### ISSUE TITLE
Team skeet not matching some sites

### ISSUE THREAD

**Issue by dappleyard** [PAhelper/PhoenixAdult.bundle#1610]
Teamskeet is not matching some sites (This girl sucks / Teen Curves / Team skeet x .... ) and if it does, does not include the videos in collections and no information is pulled

1. Scene URL: https://www.teamskeet.com/movies/it-turns-her-on
2. Filename : Thisgirlsucks-It Turns Her On

2022-09-18 18:05:55,640 (2948) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** Thisgirlsucks It Turns Her On
2022-09-18 18:05:55,640 (2948) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Thisgirlsucks It Turns Her On
2022-09-18 18:05:55,644 (2948) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Thisgirlsucks It Turns Her On
2022-09-18 18:05:55,650 (2948) :  INFO (logkit:16) - ^^^^^^^ siteNum: 199
2022-09-18 18:05:55,650 (2948) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2022-09-18 18:05:55,651 (2948) :  INFO (logkit:16) - Search Title (before date processing): It Turns Her On
2022-09-18 18:05:55,651 (2948) :  INFO (logkit:16) - {'siteName': 'thisgirlsucks', 'searchDate': None, 'siteNum': 199, 'searchTitle': 'It Turns Her On'}
2022-09-18 18:05:55,651 (2948) :  INFO (logkit:16) - SearchData.title: It Turns Her On
2022-09-18 18:05:55,651 (2948) :  INFO (logkit:16) - SearchData.filename: thisgirlsucks-it turns her on
2022-09-18 18:05:55,651 (2948) :  INFO (logkit:16) - Provider: networkTeamSkeet
2022-09-18 18:05:55,651 (2948) :  INFO (logkit:16) - Using Google Search "site:teamskeet.com It Turns Her On"
2022-09-18 18:05:55,651 (2948) :  INFO (logkit:16) - Google Search Error
2022-09-18 18:05:55,654 (2948) :  INFO (logkit:16) - Requesting GET "https://www.teamskeet.com"
2022-09-18 18:05:55,936 (2948) :  INFO (logkit:16) - FlareSolverr
2022-09-18 18:05:55,937 (2948) :  INFO (logkit:16) - Requesting POST "http://localhost:8191/v1"
2022-09-18 18:06:00,010 (2948) :  INFO (logkit:16) - CloudScraper
2022-09-18 18:06:00,209 (2948) :  INFO (logkit:16) - ReqBin
2022-09-18 18:06:00,210 (2948) :  INFO (logkit:16) - Requesting POST "https://api.reqbin.com/api/v1/requests"
2022-09-18 18:06:00,825 (2948) :  INFO (logkit:16) - Requesting GET "None-videoscontent/_search?q=it-turns-her-on"
2022-09-18 18:06:00,826 (2948) :  ERROR (logkit:22) - Traceback (most recent call last):
  File "C:\Users\apple\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 109, in search
    provider.search(results, lang, siteNum, search)
  File "C:\Users\apple\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkTeamSkeet.py", line 54, in search
    detailsPageElements = getDataFromAPI(dbURL, sceneType, sceneName, siteNum)
  File "C:\Users\apple\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkTeamSkeet.py", line 24, in getDataFromAPI
    data = data.json()
  File "C:\Users\apple\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "E:\Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "E:\Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "E:\Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "E:\Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\scanner.py", line 122, in scan_once
    return _scan_once(string, idx)
  File "E:\Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\scanner.py", line 87, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2022-09-18 18:06:00,828 (2948) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2022-09-18 18:06:00,828 (2948) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes

**Comment by diamondpete** [comment]
TeamSkeet has an anti-scraping setup. You have to try multiple times for the request to go through. After the match you may need to refresh the metadata several times to get it to finish the matching.

**Comment by kkycble** [comment]
Same with https://www.teamskeet.com/movies/gamer-girl-skills-tested. No matter how I tried it just won't come up. Only using the string "Teamskeet - Eva Elfie" would possibly give one result, but it's the wrong scene.
