### ISSUE TITLE
Naughty America not matching

### ISSUE THREAD

**Issue by refractive2** [PAhelper/PhoenixAdult.bundle#1621]
Can't match any Naughty America sites at the moment. As an example, I provide logs for Katalina Mills' scene at My Dad's Hot Girlfriend.

Scene URL: https://www.naughtyamerica.com/scene/katalina-mills-fucking-in-the-bed-with-her-bubble-butt-20529
File name: `My Dad's Hot Girlfriend - 2015-12-15 - Katalina Mills.mp4`
Log file is below:
```
2022-09-29 22:38:08,434 (7fc054d24b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0Cjk1MDJzMgppZHM1MwpNeSBEYWQncyBIb3QgR2lybGZyaWVuZCAtIDIwMTUtMTItMTUgLSBLYXRhbGluYSBNaWxsc3M0Cm5hbWVuczQKeWVhcnIwCg__
2022-09-29 22:38:08,435 (7fc054d24b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2022-09-29 22:38:08,436 (7fc054d24b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCnhuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM0Cjk1MDJzMgppZHM1MwpNeSBEYWQncyBIb3QgR2lybGZyaWVuZCAtIDIwMTUtMTItMTUgLSBLYXRhbGluYSBNaWxsc3M0Cm5hbWVuczQKeWVhcnIwCg__
2022-09-29 22:38:08,436 (7fc054d24b38) :  INFO (agentkit:961) - Searching for matches for {'year': None, 'id': '9502', 'name': "My Dad's Hot Girlfriend - 2015-12-15 - Katalina Mills"}
2022-09-29 22:38:08,437 (7fc054d24b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/9502/tree'
2022-09-29 22:38:08,447 (7fc054d24b38) :  INFO (__init__:68) - ***MEDIA TITLE [from media.name]*** My Dad's Hot Girlfriend - 2015-12-15 - Katalina Mills
2022-09-29 22:38:08,447 (7fc054d24b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: My Dad's Hot Girlfriend - 2015-12-15 - Katalina Mills
2022-09-29 22:38:08,465 (7fc054d24b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: My Dad's Hot Girlfriend - 2015-12-15 - Katalina Mills
2022-09-29 22:38:08,476 (7fc054d24b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 15
2022-09-29 22:38:08,476 (7fc054d24b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2022-09-29 22:38:08,480 (7fc054d24b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): 2015 12 15 Katalina Mills
2022-09-29 22:38:08,480 (7fc054d24b38) :  INFO (__init__:70) - {'siteName': 'mydadshotgirlfriend', 'searchDate': '2015-12-15', 'siteNum': 15, 'searchTitle': 'Katalina Mills'}
2022-09-29 22:38:08,481 (7fc054d24b38) :  INFO (PAsearchData:23) - SearchData.title: Katalina Mills
2022-09-29 22:38:08,481 (7fc054d24b38) :  INFO (PAsearchData:26) - SearchData.date: 2015-12-15
2022-09-29 22:38:08,481 (7fc054d24b38) :  INFO (__init__:107) - Provider: siteNaughtyAmerica
2022-09-29 22:38:08,483 (7fc054d24b38) :  INFO (PAutils:182) - Requesting POST "https://i6p9q9r18e-3.algolianet.com/1/indexes/*/queries?x-algolia-application-id=I6P9Q9R18E&x-algolia-api-key=08396b1791d619478a55687b4deb48b4"
2022-09-29 22:38:08,488 (7fc054d24b38) :  ERROR (__init__:111) - Traceback (most recent call last):
  File "/var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 109, in search
    provider.search(results, lang, siteNum, search)
  File "/var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteNaughtyAmerica.py", line 53, in search
    searchResults = getAlgolia(url, 'nacms_combined_production', 'query=' + searchData.title)
  File "/var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteNaughtyAmerica.py", line 10, in getAlgolia
    data = PAutils.HTTPRequest(url, headers=headers, params=params).json()
  File "/var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Libraries/Shared/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/volume1/@appstore/PlexMediaServer/Resources/Python/lib/python2.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/volume1/@appstore/PlexMediaServer/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/volume1/@appstore/PlexMediaServer/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2022-09-29 22:38:08,489 (7fc054d24b38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2022-09-29 22:38:08,490 (7fc054d24b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
```

**Comment by pedrolara-boop** [comment]
Same here
`
2022-10-19 14:31:27,823 (7f794f490b38) :  DEBUG (runtime:88) - Sending packed state data (112 bytes)
2022-10-19 14:31:27,824 (7f794f490b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2022-10-19 14:35:08,114 (7f794f490b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjExMTI5N3MyCmlkczMyCk5hbSBrYXlsZXluaWtraXNhdmFubmFoZGFuLTMxNTA1czQKbmFtZW5zNAp5ZWFycjAK
2022-10-19 14:35:08,116 (7f794f490b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2022-10-19 14:35:08,117 (7f794f490b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.phoenixadult/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M1Ck1vdmllczEwCm1lZGlhX3R5cGUzCnM2CjExMTI5N3MyCmlkczMyCk5hbSBrYXlsZXluaWtraXNhdmFubmFoZGFuLTMxNTA1czQKbmFtZW5zNAp5ZWFycjAK
2022-10-19 14:35:08,118 (7f794f490b38) :  INFO (agentkit:961) - Searching for matches for {'year': None, 'id': '111297', 'name': 'Nam kayleynikkisavannahdan-31505'}
2022-10-19 14:35:08,118 (7f794f490b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/111297/tree'
2022-10-19 14:35:08,139 (7f794f490b38) :  INFO (__init__:68) - ***MEDIA TITLE [from media.name]*** Nam kayleynikkisavannahdan-31505
2022-10-19 14:35:08,139 (7f794f490b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Nam kayleynikkisavannahdan-31505
2022-10-19 14:35:08,156 (7f794f490b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: NaughtyAmerica kayleynikkisavannahdan-31505
2022-10-19 14:35:08,177 (7f794f490b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 42
2022-10-19 14:35:08,177 (7f794f490b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2022-10-19 14:35:08,182 (7f794f490b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): Kayleynikkisavannahdan 31505
2022-10-19 14:35:08,183 (7f794f490b38) :  INFO (__init__:70) - {'siteName': 'naughtyamerica', 'searchDate': None, 'siteNum': 42, 'searchTitle': 'Kayleynikkisavannahdan 31505'}
2022-10-19 14:35:08,184 (7f794f490b38) :  INFO (PAsearchData:23) - SearchData.title: Kayleynikkisavannahdan 31505
2022-10-19 14:35:08,184 (7f794f490b38) :  INFO (__init__:107) - Provider: siteNaughtyAmerica
2022-10-19 14:35:08,187 (7f794f490b38) :  INFO (PAutils:182) - Requesting POST "https://i6p9q9r18e-3.algolianet.com/1/indexes/*/queries?x-algolia-application-id=I6P9Q9R18E&x-algolia-api-key=08396b1791d619478a55687b4deb48b4"
2022-10-19 14:35:08,197 (7f794f490b38) :  ERROR (__init__:111) - Traceback (most recent call last):
  File "/var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 109, in search
    provider.search(results, lang, siteNum, search)
  File "/var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteNaughtyAmerica.py", line 64, in search
    score = 100 - Util.LevenshteinDistance(searchData.date, releaseDate)
  File "/var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteNaughtyAmerica.py", line 10, in getAlgolia
    data = PAutils.HTTPRequest(url, headers=headers, params=params).json()
  File "/var/packages/PlexMediaServer/shares/PlexMediaServer/AppData/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Libraries/Shared/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/volume1/@appstore/PlexMediaServer/Resources/Python/lib/python2.7/site-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/volume1/@appstore/PlexMediaServer/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/volume1/@appstore/PlexMediaServer/Resources/Python/lib/python2.7/site-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by pedrolara-boop** [comment]
Since the last commit it works only if using the scene-ID
