### ISSUE TITLE
Critical error on startup - nothing matches

### ISSUE THREAD

**Issue by StockportJambo** [PAhelper/PhoenixAdult.bundle#1763]
For the past 5 days or so, the plugin has refused to work. I've never had any issue with it before, and nothing has changed server-side as far as I'm aware. I've tried Googling the issue, and not found a solution. It may be nothing to do with Phoenix.Adult, but it's the only plugin I use. so I thought I'd ask here if anyone knows. 

Here's the log:

`
2023-04-09 20:59:29,641 (2078) :  DEBUG (networking:143) - Requesting http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-04-09 20:59:29,812 (2078) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-04-09 20:59:29,812 (2078) :  CRITICAL (core:574) - Exception getting hosted resource hashes (most recent call last):
  File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-6f393eda1\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-6f393eda1\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 242, in content
    return self.__str__()
  File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-6f393eda1\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 220, in __str__
    self.load()
  File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-6f393eda1\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 158, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
`

**Comment by StockportJambo** [comment]
More Phoenix.bundle specific errors - this is what happens whenever I try and do a match.

`2023-04-09 22:35:34,539 (2d5c) :  INFO (logkit:16) - Provider: networkMetadataAPI
2023-04-09 22:35:34,539 (2d5c) :  ERROR (logkit:22) - Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 121, in search
    provider.search(results, lang, siteNum, search)
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkMetadataAPI.py", line 27, in search
    searchResults = getDataFromAPI(url)
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\networkMetadataAPI.py", line 13, in getDataFromAPI
    req = PAutils.HTTPRequest(url, headers=headers)
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\PAutils.py", line 178, in HTTPRequest
    headers['User-Agent'] = getUserAgent(fixed_useragent)
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\PAutils.py", line 22, in getUserAgent
    ua = fake_useragent.UserAgent(fallback=UserAgent)
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\fake_useragent\fake.py", line 69, in __init__
    self.load()
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\fake_useragent\fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\fake_useragent\utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\fake_useragent\utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\fake_useragent\utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\fake_useragent\utils.py", line 67, in get
    context=context,
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 1241, in https_open
    context=self._context)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\urllib2.py", line 1167, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\httplib.py", line 1274, in __init__
    context = ssl._create_default_https_context()
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\ssl.py", line 445, in create_default_context
    context.load_default_certs(purpose)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\ssl.py", line 412, in load_default_certs
    self._load_windows_store_certs(storename, purpose)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\ssl.py", line 404, in _load_windows_store_certs
    self.load_verify_locations(cadata=certs)
SSLError: unknown error (_ssl.c:2938)
`

**Comment by diamondpete** [comment]
This is a Plex bug created in server version 1.32.0.6865+. The bug happens outside the execution of the metadata scraper, so only the Plex devs can resolve. I suggest you open a ticket on the Plex forums (I have no idea if any other custom metadata scrapers have this issue, but I haven't had a chance to report it). Downgrading the server to 1.31.3.6868 will resolve the issue temporarily until a proper fix is provided.

**Comment by StockportJambo** [comment]
Thanks for the response. I did wonder if it was Plex at fault - think it recently updated, and it's been broken since. I'll wait a bit to see if they fix it, if not, I'll revert back to an older version.

**Comment by kkycble** [comment]
> Thanks for the response. I did wonder if it was Plex at fault - think it recently updated, and it's been broken since. I'll wait a bit to see if they fix it, if not, I'll revert back to an older version.

been having the same problem. The thing is I don't know how to safely rollback my PMS version without damaging my settings and metadata :(

**Comment by xnwabudike** [comment]
It may be worth reopening this issue as a Plex Employee claims that they will NOT be updating python to fix this.

Source: https://forums.plex.tv/t/1-32-x-breaks-plugins-openssl/838323

**Comment by diamondpete** [comment]
[PlexPlug-inFramework.pdf](https://github.com/PAhelper/PhoenixAdult.bundle/files/11287310/PlexPlug-inFramework.pdf)

Well, I'm hoping they resolve it. Basically, In PAutils.HTTPRequest needs to have requests.request replaced with HTTP.Request defined in the Plex Plug-In Framework and would pretty much requires a complete rework of the scrapers.

**Comment by StockportJambo** [comment]
In the latest 1.32.1.6999 version, they claim to have fixed it, but it appears still broken for Phoenix.Adult at least.

Seems like a bit of a standoff at present.
