### ISSUE TITLE
Nubiles Porn network stopped working

### ISSUE THREAD

**Issue by captaincoitus** [PAhelper/PhoenixAdult.bundle#1787]
**Describe the bug**
PA Agent is unable to fetch metadata from the NubilesPorn Network. I check in the logs and there is a xml parsing issue.

**Include**
1. Scene URL: https://cumswappingsis.com/video/watch/171248
2. File Name: Cum Swapping Sis - 171248 - My Stepsis and I Share Everything
3. Log File: 
    `2023-05-20 17:39:14,216 (154ef5ad3b38) :  DEBUG (preferences:178) - Loaded the user preferences for com.plexapp.agents.phoenixadult
2023-05-20 17:39:14,217 (154ef5ad3b38) :  INFO (__init__:68) - ***MEDIA TITLE [from media.name]*** Cum Swapping Sis 171248 My Stepsis and I Share Everything
2023-05-20 17:39:14,217 (154ef5ad3b38) :  INFO (PAsearchSites:51) - mediaTitle w/ possible abbreviation: Cum Swapping Sis 171248 My Stepsis and I Share Everything
2023-05-20 17:39:14,221 (154ef5ad3b38) :  INFO (PAsearchSites:59) - mediaTitle w/ possible abbrieviation fixed: Cum Swapping Sis 171248 My Stepsis and I Share Everything
2023-05-20 17:39:14,225 (154ef5ad3b38) :  INFO (PAsearchSites:71) - ^^^^^^^ siteNum: 1397
2023-05-20 17:39:14,225 (154ef5ad3b38) :  INFO (PAsearchSites:72) - ^^^^^^^ Shortening Title
2023-05-20 17:39:14,227 (154ef5ad3b38) :  INFO (PAsearchSites:96) - Search Title (before date processing): 171248 My Stepsis and I Share Everything
2023-05-20 17:39:14,227 (154ef5ad3b38) :  INFO (__init__:70) - {'siteName': 'cumswappingsis', 'searchDate': None, 'siteNum': 1397, 'searchTitle': '171248 My Stepsis and I Share Everything'}
2023-05-20 17:39:14,228 (154ef5ad3b38) :  INFO (PAsearchData:23) - SearchData.title: 171248 My Stepsis and I Share Everything
2023-05-20 17:39:14,228 (154ef5ad3b38) :  INFO (PAsearchData:29) - SearchData.filename: Cum Swapping Sis - 171248 - My Stepsis And I Share Everything
2023-05-20 17:39:14,229 (154ef5ad3b38) :  INFO (__init__:107) - Provider: networkNubiles
2023-05-20 17:39:34,542 (154ef5ad3b38) :  INFO (PAutils:183) - Requesting GET "https://cumswappingsis.com/video/watch/171248"
2023-05-20 17:39:39,559 (154ef5ad3b38) :  INFO (PAutils:205) - saveRequest Error
2023-05-20 17:39:39,559 (154ef5ad3b38) :  CRITICAL (data:159) - Error parsing with lxml, falling back to soupparser (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/data.py", line 157, in from_string
    return html.fromstring(markup, parser=html_parser)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/lxml/html/__init__.py", line 634, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/site-packages/lxml/html/__init__.py", line 535, in document_fromstring
    "Document is empty")
ParserError: Document is empty

2023-05-20 17:39:39,561 (154ef5ad3b38) :  ERROR (__init__:111) - Traceback (most recent call last):
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 109, in search
    provider.search(results, lang, siteNum, search)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkNubiles.py", line 28, in search
    detailsPageElements = detailsPageElements.xpath('//div[contains(@class, "content-pane-title")]')[0]
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-248a2daf0/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
IndexError: list index out of range
`
Full log file: 
[com.plexapp.agents.phoenixadult.log](https://github.com/PAhelper/PhoenixAdult.bundle/files/11523253/com.plexapp.agents.phoenixadult.log)

**Comment by diamondpete** [comment]
Match is currently working for me, and I am pretty sure you can get IP banned from Nubiles for a week or two. Has happened to me before. Try going to their sites in a web browser.
