### ISSUE TITLE
Network18 (Fit18 / Thicc18) No Longer Matching

### ISSUE THREAD

**Issue by xnwabudike** [PAhelper/PhoenixAdult.bundle#1930]
**Describe the bug**
Something seems to be failing with the API requests. I can make it work by switching to scraping the sites directly like it used to but thought that someone might know how to fix the current implementation quickly.

**Include**
File Name / Scene Name: Any
Log:
```
2024-07-25 12:23:55,786 (730) :  INFO (logkit:16) - ***MEDIA TITLE [from media.name]*** Fit18 Elsa Violet Initial Fitness Casting and Creampie
2024-07-25 12:23:55,786 (730) :  INFO (logkit:16) - mediaTitle w/ possible abbreviation: Fit18 Elsa Violet Initial Fitness Casting and Creampie
2024-07-25 12:23:55,795 (730) :  INFO (logkit:16) - mediaTitle w/ possible abbrieviation fixed: Fit18 Elsa Violet Initial Fitness Casting and Creampie
2024-07-25 12:23:55,802 (730) :  INFO (logkit:16) - ^^^^^^^ siteNum: 1336
2024-07-25 12:23:55,802 (730) :  INFO (logkit:16) - ^^^^^^^ Shortening Title
2024-07-25 12:23:55,805 (730) :  INFO (logkit:16) - Search Title (before date processing): Elsa Violet Initial Fitness Casting and Creampie
2024-07-25 12:23:55,805 (730) :  INFO (logkit:16) - {'siteName': 'fit18', 'searchDate': None, 'siteNum': 1336, 'searchTitle': 'Elsa Violet Initial Fitness Casting and Creampie'}
2024-07-25 12:23:55,805 (730) :  INFO (logkit:16) - SearchData.title: Elsa Violet Initial Fitness Casting and Creampie
2024-07-25 12:23:55,805 (730) :  INFO (logkit:16) - SearchData.filename: Fit18 - Elsa Violet Initial Fitness Casting and Creampie
2024-07-25 12:23:55,805 (730) :  INFO (logkit:16) - Provider: network18
2024-07-25 12:23:59,811 (730) :  INFO (logkit:16) - Requesting POST "https://fit18.team18.app/graphql"
2024-07-25 12:23:59,880 (730) :  ERROR (logkit:22) - Traceback (most recent call last):
  File "C:\Plex\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\__init__.py", line 109, in search
    provider.search(results, lang, siteNum, search)
  File "C:\Plex\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network18.py", line 20, in search
    searchResults = getGraphQL(searchQuery, 'query', searchData.title, siteNum)['search']['search']['result']
  File "C:\Plex\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Code\network18.py", line 14, in getGraphQL
    data = PAutils.HTTPRequest(PAsearchSites.getSearchSearchURL(siteNum), headers=headers, params=params).json()
  File "C:\Plex\Plex Media Server\Plug-ins\PhoenixAdult.bundle\Contents\Libraries\Shared\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Program Files\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "C:\Program Files\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\scanner.py", line 122, in scan_once
    return _scan_once(string, idx)
  File "C:\Program Files\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\scanner.py", line 87, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by xnwabudike** [comment]
👍
